name: JS Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       CODECOV_TOKEN: ${{ secrets. CODECOV_TOKEN}}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: install
      working-directory: ./frontend
      run: yarn

    - name: Run test
      working-directory: ./frontend
      run: yarn test --coverage --watchAll=false

    - name: Send Coverage
      working-directory: ./frontend
      run: bash <(curl -s https://codecov.io/bash) -cF javascript -f coverage/clover.xml
